development:
  key:    "2466949139"
  secret: "657585d897707c407b15e4ad84684a93"
  url:    "http://yoursite.com"
  callback: "http://localhost:3000/syncs/sina/callback"
production:
  key:    "you api key"
  secret: "your secret"
  url:    "http://yoursite.com"
  callback: "http://localhost:3000/syncs/sina/callback"
